c#define ONLY_RAY_TRACING
#define RADGRID_TWODIM
c#define RADGRID_ONEDIM
#define INCLUDE_LINES
#define INCLUDE_DUST
#define LINE_DUSTCONT
c#define LINE_FREQDEP_DUST
#define SUBGRID
#define COORD_SPHERICAL
#define ESC_MINIMAL_EXTENSION 
#define FRSIZE_X      300
#define FRSIZE_Y      400
#define FRSIZE_FREQ      1601
#define FRSIZE_MU   43
#define FRSIZE_PHI  16
#define FRSIZE_CHAR 24
#define FRSIZE_DRR         4
#define FRSIZE_INF_PHI  400
#define FRSIZE_INF_R    (8*FRSIZE_X+100)
#define FRSIZE_INF_X      120
#define FRSIZE_INF_Y      120
#define DUST_SPECIES_MAX 2
#define DUST_SIZE_MAX    1
#define DUST_TRANGE_MAX  1
#define DUST_OPAC_TEMPDEP
#define MOLECULAR_DATA_DIR   '.'
#define SZ_LINEPROFILE       1601
#define SZ_LINEPROFILE_SMALL 40
#define SZ_NLINES            1000
#define SZ_NLEVELS           1000
#define SZ_NCOLTRANS         30
#define SZ_NCTTEMP           10
#define LINE_VELOCITIES
#define SMALL_MEMORY
#define MIRROR_THETA
#define MIRROR_PHI
#define INTERPOL_PHI_3
#define INTERPOL_THETA_3
#define INTERPOL_SRC_1
#define INTERPOL_FREQ_1
#define SRCQDR_PNT_2 
#define ALI_PNT_2
#define SAFETY_CHECKS_ACTIVE
#define SAFETY_CHECK_TAUMAX 1.d5
#define SHORTCHAR_EPS  1.d-10
#define TELESC_EPS     1.d-10
#define SHORTCHAR_NEWSTYLE
#define FRSIZE_SRC_BK  4
#define MAXRAYNR       1200000
#define FRSIZE_CAM_MU  100
#define FRSIZE_CAM_PHI 128
#define LEVTHRES 1d-3
#define NONREDUNDANT
#define CENTRAL_SOURCE
#define DEBUG_FILLINTENS
#define LINUXVERSION
c#define SAVE_IMCIR

#define TRMAXFIL 500
c#define MONITOR_CHARINT
c#define MONITOR_INU 1
